// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LineControlCenter.Domain.Compliance;
using LineControlCenter.Domain.Safety;
using LineControlCenter.Domain.Mes;
using Microsoft.EntityFrameworkCore;

namespace LineControlCenter.Infrastructure.Data;

public sealed partial class PostgresqlDbContext : DbContext
{
    public PostgresqlDbContext(DbContextOptions<PostgresqlDbContext> options)
        : base(options)
    {
    }

    public DbSet<LccSafetyTbl>    LccSafetyTbls    { get; set; }
    public DbSet<LccNcrcarsTbl>   LccNcrCarsTbls   { get; set; }
    public DbSet<LccQrqcTicket>   LccQrqcTickets   { get; set; }
    public DbSet<JcasMainTbl>     JcasMainTbls     { get; set; }
    public DbSet<JcasCategoryTbl> JcasCategoryTbls { get; set; }
    public DbSet<JcasCustomerTbl> JcasCustomerTbls { get; set; }
    public DbSet<MesMain>      MesMains      { get; set; }
    public DbSet<MesRouteStep> MesRouteSteps { get; set; }
    public DbSet<MesCustomer>  MesCustomers  { get; set; }
    public DbSet<MesFamily>    MesFamilies   { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresEnum("efai", "approval_status_enum", new[] { "Pending", "Approve", "Reject" })
            .HasPostgresEnum("efai", "approval_status_enum_new", new[] { "Pending", "Approve", "Reject" })
            .HasPostgresEnum("efai", "checklist_qa_final_validation_status_enum", new[] { "Pending Verification", "Verification Complete", "Verification Partially Complete" })
            .HasPostgresEnum("efai", "checklist_section_status_enum", new[] { "Pending Update", "Pending Section Verification", "Section Verified", "Reroute", "Section Submitted" })
            .HasPostgresEnum("efai", "checklist_status_enum", new[] { "In Progress", "Pending Checklist Validation", "Pending Dept Approval", "Complete", "Cancelled", "Not Submitted", "Not Submitted*", "In Progress (Reroute)" })
            .HasPostgresEnum("efai", "notice_status_enum", new[] { "active", "inactive" })
            .HasPostgresEnum("efai", "overall_checklist_status_enum", new[] { "Not Submitted", "In Progress", "Overdue", "Complete", "Cancelled" })
            .HasPostgresEnum("efai", "user_status_enum", new[] { "active", "inactive" })
            .HasPostgresEnum("efai", "verification_status_enum", new[] { "OK", "NG" })
            .HasPostgresExtension("citext");

        modelBuilder.Entity<LccSafetyTbl>(entity =>
        {
            entity.HasKey(e => e.SafetyNoId).HasName("lcc_safety_tbl_pk");
            entity.Ignore(e => e.Id);
            entity.Ignore(e => e.DomainEvents);

            entity.ToTable("lcc_safety_tbl", "lcc");

            entity.Property(e => e.SafetyNoId)
                .HasColumnType("citext")
                .HasColumnName("safety_no_id");
            entity.Property(e => e.CapaOrIpNo)
                .HasColumnType("citext")
                .HasColumnName("capa_or_ip_no");
            entity.Property(e => e.CreatedDatetime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_datetime");
            entity.Property(e => e.HighPotential).HasColumnName("high_potential");
            entity.Property(e => e.IncidentDatetime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("incident_datetime");
            entity.Property(e => e.IncidentTitle)
                .HasColumnType("citext")
                .HasColumnName("incident_title");
            entity.Property(e => e.InjuryOrIllnessCauseDirect)
                .HasColumnType("citext")
                .HasColumnName("injury_or_illness_cause_direct");
            entity.Property(e => e.InjuryOrIllnessClassification)
                .HasColumnType("citext")
                .HasColumnName("injury_or_illness_classification");
            entity.Property(e => e.LostTimeDays).HasColumnName("lost_time_days");
            entity.Property(e => e.RecordableInjuryOrIllness).HasColumnName("recordable_injury_or_illness");
            entity.Property(e => e.Region)
                .HasColumnType("citext")
                .HasColumnName("region");
            entity.Property(e => e.RestrictionOrTransferDays).HasColumnName("restriction_or_transfer_days");
            entity.Property(e => e.Sector)
                .HasColumnType("citext")
                .HasColumnName("sector");
            entity.Property(e => e.Segment)
                .HasColumnType("citext")
                .HasColumnName("segment");
            entity.Property(e => e.Severity)
                .HasColumnType("citext")
                .HasColumnName("severity");
            entity.Property(e => e.Site)
                .HasColumnType("citext")
                .HasColumnName("site");
            entity.Property(e => e.Status)
                .HasColumnType("citext")
                .HasColumnName("status");
            entity.Property(e => e.TypeOfIncident)
                .HasColumnType("citext")
                .HasColumnName("type_of_incident");
            entity.Property(e => e.TypeOfInjuryOrIllness)
                .HasColumnType("citext")
                .HasColumnName("type_of_injury_or_illness");
        });

        modelBuilder.Entity<LccNcrcarsTbl>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("lcc_ncrcars_tbl", "lcc");
            entity.Ignore(e => e.Id);
            entity.Ignore(e => e.DomainEvents);

            entity.Property(e => e.AcknowledgeDate)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("acknowledge_date");
            entity.Property(e => e.Bay)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("bay");
            entity.Property(e => e.CarOwner)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("car_owner");
            entity.Property(e => e.ClosureAging)
                .HasColumnType("character varying")
                .HasColumnName("closure_aging");
            entity.Property(e => e.ClosureDate)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("closure_date");
            entity.Property(e => e.ClosureStatus)
                .HasColumnType("character varying")
                .HasColumnName("closure_status");
            entity.Property(e => e.Customer)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("customer");
            entity.Property(e => e.Department)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("department");
            entity.Property(e => e.IssueBy)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("issue_by");
            entity.Property(e => e.IssueDate)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("issue_date");
            entity.Property(e => e.NcrType)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("ncr_type");
            entity.Property(e => e.NcrcarNo)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("ncrcar_no");
            entity.Property(e => e.NcrcarNoId).HasColumnName("ncrcar_no_id");
            entity.Property(e => e.Plant)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("plant");
            entity.Property(e => e.ProblemDescription)
                .IsRequired()
                .HasColumnType("citext")
                .HasColumnName("problem_description");
            entity.Property(e => e.ProblemStatement)
                .IsRequired()
                .HasColumnType("citext")
                .HasColumnName("problem_statement");
            entity.Property(e => e.ProblemStatementCategory)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("problem_statement_category");
            entity.Property(e => e.RespondedAging)
                .HasColumnType("character varying")
                .HasColumnName("responded_aging");
            entity.Property(e => e.ResponseStatus)
                .HasColumnType("character varying")
                .HasColumnName("response_status");
            entity.Property(e => e.StationArea)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("station_area");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("status");
        });

        modelBuilder.Entity<LccQrqcTicket>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("lcc_qrqc_tickets_pkey");
            entity.Ignore(e => e.DomainEvents);

            entity.ToTable("lcc_qrqc_tickets", "lcc");

            entity.Property(e => e.Id)
                .HasColumnName("id")
                .ValueGeneratedOnAdd();
            entity.Property(e => e.BayNoId).HasColumnName("bay_no_id");
            entity.Property(e => e.QrapId)
                .HasColumnType("citext")
                .HasColumnName("qrap_id");
            entity.Property(e => e.CreationDate)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("creation_date");
            entity.Property(e => e.TicketId).HasColumnName("ticket_id");
            entity.Property(e => e.Batch)
                .HasColumnType("citext")
                .HasColumnName("batch");
            entity.Property(e => e.Bay)
                .HasColumnType("citext")
                .HasColumnName("bay");
            entity.Property(e => e.Status)
                .HasColumnType("citext")
                .HasColumnName("status");
            entity.Property(e => e.Customer)
                .HasColumnType("citext")
                .HasColumnName("customer");
            entity.Property(e => e.Step)
                .HasColumnType("citext")
                .HasColumnName("step");
            entity.Property(e => e.UpdatedDatetime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_datetime");
            entity.Property(e => e.AgingDays)
                .HasColumnName("aging_days")
                .HasDefaultValue(0);
            entity.Property(e => e.Process)
                .HasColumnType("citext")
                .HasColumnName("process");
            entity.Property(e => e.Symptom)
                .HasColumnType("citext")
                .HasColumnName("symptom");
        });

        modelBuilder.Entity<JcasActionTbl>(entity =>
        {
            entity.HasKey(e => e.ActionNoId).HasName("jcas_action_tbl_pk");
            entity.Ignore(e => e.Id);
            entity.Ignore(e => e.DomainEvents);

            entity.ToTable("jcas_action_tbl", "jcas");

            entity.HasIndex(e => e.JcasRecordNumber, "IX_jcas_action_tbl_jcas_record_number");

            entity.Property(e => e.ActionNoId).HasColumnName("action_no_id");
            entity.Property(e => e.Action)
                .IsRequired()
                .HasColumnName("action");
            entity.Property(e => e.JcasRecordNumber)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("jcas_record_number");
            entity.Property(e => e.Owner)
                .IsRequired()
                .HasColumnName("owner");
            entity.Property(e => e.Status)
                .HasDefaultValue(true)
                .HasComment("true = active; false = canceled")
                .HasColumnName("status");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasColumnType("citext")
                .HasColumnName("type");
            entity.Property(e => e.UpdatedDatetime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_datetime");

            entity.HasOne(d => d.JcasRecordNumberNavigation).WithMany(p => p.JcasActionTbls)
                .HasForeignKey(d => d.JcasRecordNumber)
                .HasConstraintName("jcas_action_tbl_jcas_main_tbl_fk");
        });

        modelBuilder.Entity<JcasCategoryTbl>(entity =>
        {
            entity.HasKey(e => e.CategoryNoId).HasName("jcas_category_tbl_pk");
            entity.Ignore(e => e.Id);
            entity.Ignore(e => e.DomainEvents);

            entity.ToTable("jcas_category_tbl", "jcas");

            entity.Property(e => e.CategoryNoId).HasColumnName("category_no_id");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasColumnType("citext")
                .HasColumnName("category_name");
            entity.Property(e => e.UpdatedDatetime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_datetime");
        });

        modelBuilder.Entity<JcasCustomerTbl>(entity =>
        {
            entity.HasKey(e => e.CustomerNoId).HasName("jcas_customer_tbl_pk");
            entity.Ignore(e => e.Id);
            entity.Ignore(e => e.DomainEvents);

            entity.ToTable("jcas_customer_tbl", "jcas");

            entity.Property(e => e.CustomerNoId).HasColumnName("customer_no_id");
            entity.Property(e => e.CustomerName)
                .IsRequired()
                .HasColumnType("citext")
                .HasColumnName("customer_name");
            entity.Property(e => e.UpdatedDatetime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_datetime");
        });

        modelBuilder.Entity<JcasMainTbl>(entity =>
        {
            entity.HasKey(e => e.JcasRecordNumber).HasName("jcas_main_tbl_pk");
            entity.Ignore(e => e.Id);
            entity.Ignore(e => e.DomainEvents);

            entity.ToTable("jcas_main_tbl", "jcas");

            entity.HasIndex(e => e.CategoryNoId, "IX_jcas_main_tbl_category_no_id");

            entity.HasIndex(e => e.CustNoId, "IX_jcas_main_tbl_cust_no_id");

            entity.Property(e => e.JcasRecordNumber)
                .HasColumnType("character varying")
                .HasColumnName("jcas_record_number");
            entity.Property(e => e.BusinessSector)
                .HasColumnType("citext")
                .HasColumnName("business_sector");
            entity.Property(e => e.CategoryNoId).HasColumnName("category_no_id");
            entity.Property(e => e.CustNoId).HasColumnName("cust_no_id");
            entity.Property(e => e.D4CompletedDate).HasColumnName("d4_completed_date");
            entity.Property(e => e.D4Owner).HasColumnName("d4_owner");
            entity.Property(e => e.D6DueDate).HasColumnName("d6_due_date");
            entity.Property(e => e.D7CompletedDate).HasColumnName("d7_completed_date");
            entity.Property(e => e.D7DueDate).HasColumnName("d7_due_date");
            entity.Property(e => e.D7IsCompleted).HasColumnName("d7_is_completed");
            entity.Property(e => e.D7IsOntime).HasColumnName("d7_is_ontime");
            entity.Property(e => e.D8Owner).HasColumnName("d8_owner");
            entity.Property(e => e.FailureMode)
                .HasColumnType("citext")
                .HasColumnName("failure_mode");
            entity.Property(e => e.FailureModeCategory)
                .HasColumnType("citext")
                .HasColumnName("failure_mode_category");
            entity.Property(e => e.InitiatingSite)
                .HasColumnType("citext")
                .HasColumnName("initiating_site");
            entity.Property(e => e.Investigation)
                .HasColumnType("citext")
                .HasColumnName("investigation");
            entity.Property(e => e.JcasCreatedDate).HasColumnName("jcas_created_date");
            entity.Property(e => e.JcasInitiator).HasColumnName("jcas_initiator");
            entity.Property(e => e.JcasOwner).HasColumnName("jcas_owner");
            entity.Property(e => e.JcasType)
                .HasColumnType("citext")
                .HasColumnName("jcas_type");
            entity.Property(e => e.JcasUrl).HasColumnName("jcas_url");
            entity.Property(e => e.Origination).HasColumnName("origination");
            entity.Property(e => e.Phase).HasColumnName("phase");
            entity.Property(e => e.ProblemDescription)
                .HasColumnType("citext")
                .HasColumnName("problem_description");
            entity.Property(e => e.ProcAffected)
                .HasColumnType("citext")
                .HasColumnName("proc_affected");
            entity.Property(e => e.ReceivingSite)
                .HasColumnType("citext")
                .HasColumnName("receiving_site");
            entity.Property(e => e.SendingSite)
                .HasColumnType("citext")
                .HasColumnName("sending_site");
            entity.Property(e => e.Severity)
                .HasColumnType("citext")
                .HasColumnName("severity");
            entity.Property(e => e.Status).HasColumnName("status");
            entity.Property(e => e.Title)
                .HasColumnType("citext")
                .HasColumnName("title");

            entity.HasOne(d => d.CategoryNo).WithMany(p => p.JcasMainTbls)
                .HasForeignKey(d => d.CategoryNoId)
                .HasConstraintName("jcas_main_tbl_jcas_category_tbl_fk");

            entity.HasOne(d => d.CustNo).WithMany(p => p.JcasMainTbls)
                .HasForeignKey(d => d.CustNoId)
                .HasConstraintName("jcas_main_tbl_jcas_customer_tbl_fk");
        });

        modelBuilder.Entity<JcasRootcauseTbl>(entity =>
        {
            entity.HasKey(e => e.RcNoId).HasName("jcas_rootcause_tbl_pk");
            entity.Ignore(e => e.Id);
            entity.Ignore(e => e.DomainEvents);

            entity.ToTable("jcas_rootcause_tbl", "jcas");

            entity.HasIndex(e => e.JcasRecordNumber, "IX_jcas_rootcause_tbl_jcas_record_number");

            entity.Property(e => e.RcNoId).HasColumnName("rc_no_id");
            entity.Property(e => e.Category)
                .IsRequired()
                .HasColumnName("category");
            entity.Property(e => e.JcasRecordNumber)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("jcas_record_number");
            entity.Property(e => e.RootCause)
                .IsRequired()
                .HasColumnName("root_cause");
            entity.Property(e => e.Status)
                .HasDefaultValue(true)
                .HasComment("true = active; false = canceled")
                .HasColumnName("status");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasColumnType("citext")
                .HasColumnName("type");
            entity.Property(e => e.UpdatedDatetime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_datetime");

            entity.HasOne(d => d.JcasRecordNumberNavigation).WithMany(p => p.JcasRootcauseTbls)
                .HasForeignKey(d => d.JcasRecordNumber)
                .HasConstraintName("jcas_rootcause_tbl_jcas_main_tbl_fk");
        });

        modelBuilder.Entity<MesMain>(entity =>
        {
            entity.HasKey(e => e.MesId).HasName("mes_main_pk");
            entity.ToTable("mes_main", "mes");

            entity.Property(e => e.MesId).HasColumnName("mes_id");
            entity.Property(e => e.RouteStepId).HasColumnName("route_step_id");
            entity.Property(e => e.SerialNumber)
                .HasColumnType("citext")
                .HasColumnName("serial_number");
            entity.Property(e => e.CustId).HasColumnName("cust_id");
            entity.Property(e => e.AssyId)
                .HasColumnType("citext")
                .HasColumnName("assy_id");
            entity.Property(e => e.FamilyId)
                .HasColumnName("family_id");
            entity.Property(e => e.TestLoop).HasColumnName("test_loop");
            entity.Property(e => e.ProcessLoop).HasColumnName("process_loop");
            entity.Property(e => e.StartTime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("start_time");
            entity.Property(e => e.EndTime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("end_time");
            entity.Property(e => e.Status)
                .HasColumnType("citext")
                .HasColumnName("status");
        });

        modelBuilder.Entity<MesRouteStep>(entity =>
        {
            entity.HasKey(e => e.RouteStepNoId).HasName("mes_route_steps_pk");
            entity.ToTable("mes_route_steps", "mes");

            entity.Property(e => e.RouteStepNoId).HasColumnName("route_step_no_id");
            entity.Property(e => e.RouteStepId).HasColumnName("route_step_id");
            entity.Property(e => e.StepInstance)
                .HasColumnType("citext")
                .HasColumnName("step_instance");
            entity.Property(e => e.CustId).HasColumnName("cust_id");
        });

        modelBuilder.Entity<MesCustomer>(entity =>
        {
            entity.HasKey(e => e.CustNoId).HasName("mes_customer_pk");
            entity.ToTable("mes_customer", "mes");

            entity.Property(e => e.CustNoId).HasColumnName("cust_no_id");
            entity.Property(e => e.CustomerName)
                .HasColumnType("citext")
                .HasColumnName("customer_name");
            entity.Property(e => e.CustomerId).HasColumnName("customer_id");
            entity.Property(e => e.DivisionText)
                .HasColumnType("citext")
                .HasColumnName("division_text");
        });

        modelBuilder.Entity<MesFamily>(entity =>
        {
            entity.HasKey(e => e.FamilyId).HasName("mes_family_pk");
            entity.ToTable("mes_family", "mes");

            entity.Property(e => e.FamilyId).HasColumnName("family_id");
            entity.Property(e => e.Family)
                .HasColumnType("citext")
                .HasColumnName("family");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}